### ISSUE TITLE
Allow the user to specify the new container ID

### ISSUE THREAD

**Issue by ebertland** [onethree7/proxmox-lxc-privilege-converter#3]
### Background

I like to organize my container IDs in a particular way. In particular, I like to use a different range for containers and virtual machines. (I'm a new proxmox user, so maybe I will discover that this is more trouble than it's worth, eventually.)

### Feature Request

Prompt the user to enter the new container ID. Provide the next free ID as the default. If the user enters a different ID from the default, check that it's free before continuing.

**Comment by ebertland** [comment]
I implemented this feature and will provide a PR in the next day or two.

**Comment by onethree7** [comment]
I love this idea Jeff
Lets do it. I could implement this quickly myself, but you mentioned you have already done it?

You of course are invited to submit that PR and if it works well and i like the style we can integrate it. 

Thank you very much for the contribution.

**Comment by ebertland** [comment]
Yes, I have the code and will make the pull request later today.

**Comment by onethree7** [comment]
I´ve added the feature in 1.0.5 
https://github.com/onethree7/proxmox-lxc-privilege-converter/commit/fb022d53b52a7e9a2868a0ec6c22dc946dedb417

Resolving the issue therefore. Thanks a lot for the suggestion again!
