### ISSUE TITLE
Why not replace the container instead of making a clone?

### ISSUE THREAD

**Issue by ebertland** [onethree7/proxmox-lxc-privilege-converter#4]
The way I used this very helpful script is to replace a container that I had originally made unprivileged with a privileged one. In some of the tutorials I found for doing this before finding this script, they recommended destroying the original container in between backup and restore.

What's the reason for keeping the original container? Are you open to a PR that allows the user to choose between replacing and cloning?

**Comment by onethree7** [comment]
Hello,
thanks as well for this suggestion. This one will not come though.

The reasoning behind that is, that an automatic "replacement" could introduce a single point of failure which could actually bring a form of Data Unavailability or even Data Loss into the equasion. We can never anticipate what a user has configured in a way that will break on conversion...

**Comment by ebertland** [comment]
Oh, I see. The restore might fail, but the original was already deleted.
